# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

resources:
  containers:
    - container: test
      type: ACR
      image: hello-world:v1
      azureSubscription: test
      resourceGroup: testacr
      registry: testacr717
      repository: hello-world

stages:
  - stage: test
    displayName: test
    jobs:
    - job: test
      steps:
      - task: Docker@2
        displayName: run image
        inputs:
         command: start
         container: test
