# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'devopsarm'
              subscriptionId: 'c7aa45a6-0b42-4d61-b5ed-e7102b6066b3'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'testdev'
              location: 'West US 2'
              templateLocation: 'URL of the file'
              csmFileLink: 'https://github.com/kagoesy/aksdevops/blob/main/ExportedTemplate-testdev/template.json'
              csmParametersFileLink: 'https://github.com/kagoesy/aksdevops/blob/main/ExportedTemplate-testdev/parameters.json'
              deploymentMode: 'Incremental'
